#!/bin/bash

if [ -d ./reci.py ]
  then
    echo "Found build tool"
  else
    echo "We need to install a build tool"
    git clone --depth 1 https://github.com/jensdpersson/reci.py.git
    echo ./reci.py >> .gitignore
fi
./reci.py/src/main/python/reci.py site
./reci.py/src/main/python/reci.py escript
chmod u+x hty
