# Generated by Erlang.mk. Edit at your own risk!

src/hty_formtree_spaf.erl:: src/hty_scan.erl; @touch $@
src/hty_formurlencoded_spaf.erl:: src/hty_percentencoding.erl src/hty_scan.erl; @touch $@

COMPILE_FIRST += hty_percentencoding hty_scan
